Repository Pigmice2733/peregrine-frontend, pull requests merged in 2022-06, with the labels that each got.

#1500 changed saved match location to a preact-state
  package-lock.json
  package.json
  src/routes/scout.tsx
Labels: enhancement, ready

#1057 Added a message for non-existent matches
  src/routes/event-match.tsx
  src/utils/format-match-key/index.ts
Labels: bug

#1512 Created a card component for error pages
  package-lock.json
  src/components/error-card.tsx
  src/routes/event-match.tsx
Labels: enhancement

#1513 404 error page
  src/components/error-card.tsx
  src/router.tsx
  src/routes/404-error.tsx
Labels: enhancement, question

#1027 Non-Existent Events
  src/api/base.ts
  src/routes/event-match.tsx
  src/routes/event-team-matches.tsx
  src/routes/event.tsx
  src/utils/use-network-cache.ts
Labels: bug
